# Docker Compose file for ELK stack

# Build with:
# docker-compose build elk

# Run with:
# docker-compose up

version: "3"

services:

  elk:
    image: busbyjon/elk-docker:arm 
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
